In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("Iris.csv")
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [3]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
data["Species"]=l.fit_transform(data["Species"])
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [4]:
X=np.array(data.iloc[:,1:-1])
y=np.array(data["Species"])

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.33)

In [12]:
from sklearn.naive_bayes import GaussianNB
b=GaussianNB().fit(x_train,y_train)

In [13]:
y_predict=b.predict(x_test)

### Accuracy check

In [14]:
print("training class accuracy",b.score(x_train,y_train))
print("testing class accuracy",b.score(x_test,y_test))

training class accuracy 0.95
testing class accuracy 0.94


In [17]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_predict))

0.94


In [15]:
from sklearn.metrics import confusion_matrix
x=confusion_matrix(y_true=y_test,y_pred=y_predict)
print(x)

[[18  0  0]
 [ 0 14  3]
 [ 0  0 15]]


In [16]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      0.82      0.90        17
           2       0.83      1.00      0.91        15

    accuracy                           0.94        50
   macro avg       0.94      0.94      0.94        50
weighted avg       0.95      0.94      0.94        50



precision:What proportion of positive identifications was actually correct?  

recall:What proportion of actual positives was identified correctly?